// GEOSITE / GEOIP 基础路由(平台无关)。放在规则链后段,负责兜底的国内外分流与广告拦截。
// 注意顺序敏感:越具体的 geosite 越靠前,最后由 GEOIP + MATCH 兜底。
export default {
        name: "geo",
        common: [
                "GEOSITE,connectivity-check,DIRECT",
                "GEOSITE,private,DIRECT",
                "GEOSITE,google-scholar,Default",
                "GEOSITE,z-library,Default",
                "GEOSITE,category-scholar-!cn,DIRECT",
                "GEOSITE,github,Default",
                "GEOSITE,onedrive,Default",
                "GEOSITE,google-gemini,AI",
                "GEOSITE,category-ai-!cn,AI",
                "GEOSITE,google,Default",
                "GEOSITE,category-ads-all,REJECT",
                "GEOSITE,microsoft@cn,DIRECT",
                "GEOSITE,microsoft,Default",
                "GEOSITE,geolocation-!cn@cn,DIRECT",
                "GEOSITE,geolocation-!cn,Default",
                "GEOSITE,geolocation-cn@!cn,Default",
                "GEOSITE,geolocation-cn,DIRECT",
                "GEOSITE,cn,DIRECT",
                "GEOSITE,tld-cn,DIRECT",
                "GEOIP,LAN,DIRECT,no-resolve",
                "GEOIP,CN,DIRECT,no-resolve",
                "MATCH,漏网之鱼",
        ],
        win: [],
        unix: [],
};
